# Generated by Django 2.0.3 on 2018-04-09 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver_movie_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Naver의 Movie ID')),
                ('title_ko', models.CharField(max_length=100, verbose_name='영화제목')),
                ('title_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('nation', models.CharField(blank=True, choices=[('KR', '한국'), ('JP', '일본'), ('CH', '중국'), ('US', '미국'), ('HK', '홍콩'), ('GB', '영국'), ('FR', '프랑스'), ('GM', '독일'), ('IT', '이탈리아'), ('TH', '태국'), ('ETC', 'None')], max_length=100, verbose_name='국가')),
                ('running_time', models.CharField(blank=True, max_length=100, verbose_name='상영시간')),
                ('film_rate', models.CharField(blank=True, max_length=100, verbose_name='상영 등급')),
                ('rank_share', models.CharField(blank=True, max_length=100, verbose_name='예매율')),
                ('audience', models.IntegerField(blank=True, null=True, verbose_name='누적관객수')),
                ('story', models.TextField(blank=True, verbose_name='줄거리')),
                ('poster_image', models.ImageField(blank=True, upload_to='poster', verbose_name='포스터 이미지')),
                ('still_cut', models.ImageField(blank=True, upload_to='still_image', verbose_name='스틸컷')),
                ('d_day', models.DateField(blank=True, max_length=50, null=True, verbose_name='개봉일')),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
