# Generated by Django 2.0.3 on 2018-03-30 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='영화제목')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('running_time', models.CharField(blank=True, max_length=100, verbose_name='상영시간')),
                ('film_rate', models.CharField(blank=True, max_length=100, verbose_name='상영 등급')),
                ('nation', models.CharField(blank=True, max_length=100, verbose_name='국가')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='장르')),
                ('intro', models.TextField(blank=True, verbose_name='소개')),
                ('rank_share', models.CharField(blank=True, max_length=100, verbose_name='예매율')),
                ('audience', models.IntegerField(blank=True, verbose_name='관객수')),
                ('Poster_image', models.ImageField(blank=True, upload_to='poster', verbose_name='포스터 이미지')),
                ('still_cut', models.ImageField(blank=True, upload_to='still_image', verbose_name='스틸컷')),
                ('d_day', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
