# Generated by Django 2.0.3 on 2018-04-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stillcut',
            options={'ordering': ['-pk']},
        ),
    ]
