# Generated by Django 2.0.3 on 2018-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_rate',
            field=models.CharField(blank=True, choices=[('all', '전체 관람가'), ('12', '12세 관람가'), ('15', '15세 관람가'), ('18', '18세 관람가'), ('limit', '청소년 관람불가'), ('ETC', '기타')], max_length=10, verbose_name='상영 등급'),
        ),
    ]
