# Generated by Django 2.0.3 on 2018-04-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='상영시간'),
        ),
    ]
