# Generated by Django 2.0.3 on 2018-04-14 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ticketing_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='예매율'),
        ),
    ]
