# Generated by Django 2.0.3 on 2018-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_created_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='제작년도'),
        ),
    ]
