# Generated by Django 2.0.3 on 2018-04-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertomovie',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='movietomember',
            name='type',
            field=models.CharField(choices=[('1', '감독'), ('2', '주연'), ('3', '조연'), ('4', '단역')], max_length=5, verbose_name='구성원 분류'),
        ),
        migrations.AlterField(
            model_name='stillcut',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='still_cuts', to='movie.Movie', verbose_name='영화'),
        ),
    ]
