# Generated by Django 2.0.3 on 2018-04-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_image_m',
            field=models.ImageField(blank=True, upload_to='poster/medium', verbose_name='포스터 이미지'),
        ),
    ]
