# Generated by Django 2.0.3 on 2018-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_image_ios',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_image_ios_small',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image_box_x3',
            field=models.ImageField(blank=True, upload_to='poster/ios/box', verbose_name='IOS box office x3'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image_eval_x3',
            field=models.ImageField(blank=True, upload_to='poster/ios/eval', verbose_name='IOS eval x3'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image_my_x3',
            field=models.ImageField(blank=True, upload_to='poster/ios/my', verbose_name='IOS mypage x3'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image_s',
            field=models.ImageField(blank=True, upload_to='poster', verbose_name='작은 포스터 이미지'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image_m',
            field=models.ImageField(blank=True, upload_to='poster', verbose_name='중간 포스터 이미지'),
        ),
    ]
