# Generated by Django 2.0.3 on 2018-04-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180417_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='traileryoutube',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traileryoutube',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_youtube', to='movie.Movie', verbose_name='영화'),
        ),
        migrations.AlterField(
            model_name='traileryoutube',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='traileryoutube',
            name='youtube_id',
            field=models.CharField(max_length=20, verbose_name='YouTube ID'),
        ),
    ]
