# Generated by Django 2.0.3 on 2018-04-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_poster_image_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_image_ios',
            field=models.ImageField(blank=True, upload_to='poster/ios', verbose_name='IOS 포스터 이미지'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image_m',
            field=models.ImageField(blank=True, upload_to='poster/medium', verbose_name='작은 포스터 이미지'),
        ),
    ]
