# Generated by Django 2.0.3 on 2018-04-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180416_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-ticketing_rate']},
        ),
    ]
