# Generated by Django 2.0.3 on 2018-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20180418_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_image_ios_small',
            field=models.ImageField(blank=True, upload_to='poster/ios', verbose_name='IOS 포스터 이미지'),
        ),
    ]
