from .box_office import *
from .eval_page import *
from .main_page import *
from .movie_detail import *
from .movie_list import *
from .search_movie import *
from .user_to_movie_create import *
from .user_to_movie_list import *
from .user_to_movie_update import *
