from .detail import *
from .email_update import *
from .img_profile import *
from .list import *
from .login import *
from .logout import *
from .mypage_top import *
from .search_user import *
from .signup import *
from .want_watched_movie_list import *
from .mypage import *
from .commented_movie_list import *